### ISSUE TITLE
Pretrained weights and training time VQ-VAE2

### ISSUE THREAD

**Issue by pvitoria** [kamenbliznashki/generative_models#2]
Hi! 
First of all congrats for the nice work.
I am wondering how long it took to train the vq-vae 2 model and the priors, and if you have the pre-trained weights from CheXpert dataset.

Best,

**Comment by pvitoria** [comment]
Also, there is any reason why you use PixelCNN for the bottom layer and PixelSnail for the top ?

Best

**Comment by kamenbliznashki** [comment]
Hi - 

Training the VAE model was quite fast and it converges pretty quickly. Training the AR priors on the other hand takes a while. In general, any of these autoregressive models take a long time. I didn't train until full convergence but just until the samples were good enough. 

Re bottom and top priors - the original paper uses PixelSNAIL for the top and PixelCNN for the bottom. PixelSNAIL is a more powerful model because of self-attention; however, it's memory footprint is much larger and you really can't use it for the larger dimensional bottom latents. 

Re weights - the experiments I saved are about 6GB for the vae and priors; if you need them badly shoot me an email and we'll figure out a way to share them.

Best
Kamen

**Comment by pvitoria** [comment]
Hi Kamen! 
Thanks for your answer.
It would be really nice if you could share the weights, I am having trubbles to train it and i would like to test some things in the prior. I will mail you!

Best,
Patricia
